# -*- coding: utf-8 -*-
"""HW_SemanticSearch_Generation_EleazarMatthew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzSxYeKK7Dw8nFcres_7hw2xbY7UHj8C

# 1. Setup and Imports
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install langchain==0.2.5 langchain-community==0.2.5 langchain_openai>=0.1.6
# !pip install openai>=1.13.3 transformers>=4.40.1 datasets>=2.18.0 accelerate>=0.27.2
# !pip install sentence-transformers==3.0.1 duckduckgo-search>=5.2.2 cohere==5.5.8
# !pip install faiss-cpu==1.8.0 rank_bm25==0.2.2
# !pip install llama-cpp-python==0.2.78 --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124
# # IMPORTANT: Make sure to restart the session after installing the packages above.

from datasets import load_dataset
from sentence_transformers import SentenceTransformer
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM
import torch
import faiss
import duckduckgo_search
import cohere
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import textwrap
from tqdm import tqdm
warnings.filterwarnings('ignore')

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Set random seeds for reproducibility
np.random.seed(42)
torch.manual_seed(42)

print("All libraries imported successfully!")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

"""# 2. Data Loading and Inspection

### What is being done?
We are loading the official ag_news dataset from Huggingface, which is a large collection of news articles, that spans 4 major categories/labels: World, Sports, Business, and Science/Technology. We will treat each articles as an internal industry brief that a consulting firm might have on file.
Down below, we're going to inspect the data to understand its structure, size, and content.

### Why is this necessary from a business analytics perspective?
Before any analysis, the consultant, obviously, has to first understand the data they are working with. It's fundamentally the equivalent of doing your "homework" or due diligence before arriving at a solution.

As seen below, we're gonna focus on the Business and Science/technology labeled articles for our knowledge base.

### How should decision-makers interpret this?
The output confirms the volume and variety of the document collection. A larger, more diverse
corpus generally means the assistant can answer a wider range of questions, but also requires
more careful quality filtering.


"""

# load the ag_news dataset from Hugging Face
dataset = load_dataset("ag_news")["train"]

# Explore dataset
print(f"Total documents in dataset: {len(dataset):,}")

#see cols
print(f"\nColumns available: {dataset.column_names}")

print(dataset)
print(dataset['text'])
print(dataset['label'])

# map the integer labels into text lables
label_map = {0: 'World', 1: 'Sports', 2: 'Business', 3: 'Science/Technology'}
print(f"\nCategory labels: {label_map}")

# we're going to convert the raw dataset into a pandas DataFrame for easier handling & manipulation
df = pd.DataFrame(dataset)
df['category'] = df['label'].map(label_map)
df.head()

# Show distribution across categories
print("Document distribution by category:")
print(df['category'].value_counts().to_string())

# Visualise the distribution
fig, ax = plt.subplots(figsize=(7, 4))
df['category'].value_counts().plot(
    kind='bar', ax=ax,
    color=['#2196F3', '#4CAF50', '#FF9800', '#9C27B0'],
    edgecolor='white'
)
ax.set_title('Document Count by Category (ag_news)', fontsize=13, fontweight='bold')
ax.set_xlabel('Category')
ax.set_ylabel('Number of Documents')
ax.tick_params(axis='x', rotation=30)
plt.tight_layout()
plt.show()

"""#### C: okay it's a well balanced dataset"""

# Display 5 sample documents so stakeholders can see the raw content
print("=" * 70)
print("SAMPLE DOCUMENTS FROM THE KNOWLEDGE ARCHIVE")
print("=" * 70)

samples = df.sample(5, random_state=42)
for i, (_, row) in enumerate(samples.iterrows(), 1):
    print(f"\n[Document {i}] Category: {row['category']}")
    print("-" * 50)
    print(textwrap.fill(row['text'], width=80))
    print()

# For this project we focus on Business and Science/Technology briefs
# as these are most relevant to a strategy consulting knowledge base.
# We sample 100 documents to keep runtime manageable (and to be able to use Cohere with my rate limits rip)
SAMPLE_SIZE  = 100
RANDOM_STATE = 42

df_subset = (
    df[df['category'].isin(['Business', 'Science/Technology'])]
    .sample(SAMPLE_SIZE, random_state=RANDOM_STATE)
    .reset_index(drop=True)
)

print(f"Working corpus size: {len(df_subset):,} documents")
print(df_subset['category'].value_counts().to_string())

"""# 3. Text Preprocessing

### What is being done?
We clean the raw document text to make it suitable for embedding and retrieval. Following
the same light-touch philosophy shown in the Chapter 8 reference notebook, we:
- Remove empty or near-empty documents
- Strip excess whitespace and newlines
- Normalise common encoding artifacts (e.g., `&amp;`)

We intentionally avoid aggressive transformations (stemming, lowercasing) because modern
embedding models perform best on natural, readable text.

### Why is this necessary from a business analytics perspective?
Garbage in, garbage out. Even a powerful AI model will return poor results if fed malformed
or incomplete text. Preprocessing ensures that documents fed into the system are clean,
complete, and meaningful: the same standard applied to any dataset before analysis.
It also prevents edge cases (e.g., blank documents) from corrupting the search index.

### How should decision-makers interpret this?
The before/after document counts show how many records were removed due to quality issues.
A small drop is normal and healthy. A large drop would signal a data quality problem that
should be investigated before deploying the system.

"""

def preprocess_text(text: str) -> str:
    """
    Light preprocessing:
    - Strip leading/trailing whitespace
    - Collapse multiple spaces and newlines
    - Remove common HTML/encoding artifacts
    """
    if not isinstance(text, str):
        return ''
    text = text.strip()
    # Collapse internal whitespace
    text = ' '.join(text.split())
    # Fix common encoding artifacts found in news datasets
    text = text.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')
    return text

# Count before preprocessing
count_before = len(df_subset)

# Apply preprocessing
df_subset['clean_text'] = df_subset['text'].apply(preprocess_text)

# Drop documents shorter than 30 characters (near-empty after cleaning)
MIN_LENGTH = 30
df_clean = (
    df_subset[df_subset['clean_text'].str.len() >= MIN_LENGTH]
    .reset_index(drop=True)
)

count_after = len(df_clean)

print(f"Documents before preprocessing : {count_before:,}")
print(f"Documents after  preprocessing : {count_after:,}")
print(f"Documents removed              : {count_before - count_after}")

# Show a before/after example
print("\nBEFORE:")
print(repr(df_subset.loc[0, 'text'][:200]))
print("\nAFTER:")
print(repr(df_clean.loc[0, 'clean_text'][:200]))

"""#### C: It appears that the Hugging Face dataset is already clean"""

# Inspect document length distribution after cleaning
df_clean['text_length'] = df_clean['clean_text'].str.len()

print("Document length statistics (characters):")
print(df_clean['text_length'].describe().round(1).to_string())

fig, ax = plt.subplots(figsize=(8, 4))
ax.hist(df_clean['text_length'], bins=50, color='#2196F3', edgecolor='white')
ax.set_title('Distribution of Document Lengths After Preprocessing', fontweight='bold')
ax.set_xlabel('Character Count')
ax.set_ylabel('Frequency')
plt.tight_layout()
plt.show()

# Extract the final list of documents for downstream use
documents = df_clean['clean_text'].tolist()
print(f"\nFinal document count ready for embedding: {len(documents):,}")

"""# 4. Document Embeddings (Chapter 8 Structure)

### What is being done?
Like the previous assignments, we will convert each document from raw text into a numerical vector (an embedding) using a pre-trained sentence transformer model using Cohere.
Each vector is a list of 384 numbers (I think this is a standard size for vector embeddings) that encodes the meaning of the document. Documents about similar topics will have vectors pointing in similar directions in this 384-dimensional space.

### Why is this necessary?
Traditional keyword search only matches exact words. If a consultant asks something like, "What drives digital transformation failure?" but a document uses words like "why technology initiatives collapse", keyword searches will miss things like these entirely. Embedding-based semantic search understands the meaning of the words; not just the words themselves, which makes it more useful for real-world business queries.


### How should decision-makers interpret this?
The output confirms the shape of the embedding matrix, which is: documents x 384 dimensions.
Each row is a docuemnt's semantic "fingerprint", if you will.
The next section uses these fingerprints to find documents that best match a query's meaning regardless of keyword/exact word overlap.

"""

# I will follow the book's usage of Cohere
# Paste your API key here. Remember to not share publicly
api_key = 'EBZ1wZpycxWoZp3bzTUjvPECwjZ31NsTh0VFfieu' # we love hard-coded API keys lmao

# Create and retrieve a Cohere API key from os.cohere.ai
co = cohere.Client(api_key)

# Embed all documents using Cohere
response = co.embed(
    texts=documents,
    model="embed-english-v3.0",
    input_type="search_document"
)

embeddings = np.array(response.embeddings)
print(f"Embedding matrix shape: {embeddings.shape}")

# Sanity check: verify that embeddings capture semantic similarity correctly
# Two documents from the same category should be more similar than
# two documents from different categories

def cosine_similarity(a, b):
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

biz_indices  = df_clean[df_clean['category'] == 'Business'].index.tolist()
tech_indices = df_clean[df_clean['category'] == 'Science/Technology'].index.tolist()

sim_same_category = cosine_similarity(
    embeddings[biz_indices[0]], embeddings[biz_indices[1]]
)
sim_diff_category = cosine_similarity(
    embeddings[biz_indices[0]], embeddings[tech_indices[0]]
)

print("Cosine Similarity Sanity Check")
print(f"  Business ↔ Business : {sim_same_category:.4f}")
print(f"  Business ↔ Science : {sim_diff_category:.4f}")

"""Review on Cosine Similarity:
Cosine similarity is a widely used similarity metric that determines how similar two data points are based on the direction they point rather than their length or size. It is especially effective in high-dimensional spaces where traditional distance-based metrics can struggle.

Computing cosine similarity requires measuring the cosine of the angle (theta) between two non-zero vectors in an inner product space. This measurement produces a cosine similarity score. Cosine similarity values range from -1 to 1:


* A cosine similarity score of 1 indicates that the vectors are pointing in the exact same direction.
* A cosine similarity score of 0 indicates that the vectors are orthogonal, meaning they have no directional similarity.
* A cosine similarity score of -1 indicates that the vectors point in exactly opposite directions.

[link text](https://www.ibm.com/think/topics/cosine-similarity#:~:text=A%20cosine%20similarity%20score%20of%201%20indicates,the%20vectors%20point%20in%20exactly%20opposite%20directions.)

# 5. Semantic Search Index

### What is being done?
We will buld a Facebook AI Similarity Search (FAISS) which is a highly efficient data structure that allows us to search through thousands of embedding vectors in milliseconds and retrieve the documents whose meaning is closest to a user's query.

Below, we will implement a `search()` function that accepts a plain English question anf returns the most relevant document excerpts.

### Why is this necessary?
Without an index, finding relevant documents would require comparing the query to every document one-by-one, which is impractical at an enterprise scale.
(I think FAISS is the same technology used in production search systems at major technology companies). Building this index transforms
our document archive from a static file store into a **queryable intelligence database**.

### How should decision-makers interpret this?
The demonstration queries show the system in action. The top-k results are the documents
the system believes are most semantically relevant to the question. Lower distance scores
indicate higher similarity. Decision-makers should review these results to build intuition
for what the system can and cannot surface before full deployment.
"""

# Build a FAISS index using L2 (Euclidean) distance
# IndexFlatL2 performs exact search — appropriate for our corpus size
dimension = embeddings.shape[1]  # 384

index = faiss.IndexFlatL2(dimension)
index.add(np.float32(embeddings))

print(f"FAISS index built successfully.")
print(f"   Total vectors indexed: {index.ntotal:,}")

import pandas as pd
# slightly modified vs textbook
def search(query: str, top_k: int = 3, verbose: bool = True) -> pd.DataFrame:

    # 1. Get the query's embedding
    query_embed = co.embed(
        texts=[query],
        model="embed-english-v3.0",
        input_type="search_query"
    ).embeddings[0]

    # 2. Retrieve the nearest neighbors
    distances, similar_item_ids = index.search(np.float32([query_embed]), top_k)

    # 3. Format the results
    results = pd.DataFrame({
        'rank'     : range(1, top_k + 1),
        'category' : [df_clean.loc[i, 'category'] for i in similar_item_ids[0]],
        'distance' : distances[0].round(4),
        'text'     : [documents[i] for i in similar_item_ids[0]]
    })

    # 4. Print and return the results
    if verbose:
        print(f" Query: '{query}'")
        print(f" Top {top_k} results:\n")
        for _, row in results.iterrows():
            print(f"  Rank {row['rank']} | {row['category']} | Distance: {row['distance']}")
            print(f"  {textwrap.fill(row['text'][:300], width=78)}")
            print()

    return results

# Demonstration query

query = "technology companies merger and acquisition"
results = search(query, verbose = True)
results["query"] = query
results

"""# 6. Retrieval Evaluation

### What is being done?
In this section, we will run three business-relevant queries through the semantic search system and evaluate the relevance of the retrieved documents.
The results will then be presented in a structured table with a written interpretation of retrieval quality.

### Why is this necessary from a business analytics perspective?
Because any analytics system deployed must first be tested before being trusted.
Retrieval evaluation is the equivalent of the model evaluation step, which basically tests whether or not the system returns genuinely relevant content of documents that merely match keywords.
Bad retireval quality will hurt our answer generation regardless of good the model is.

### How should decision-makers interpret this?
Review the retrieved snippets for each query and ask: *"If I were a consultant researching
this topic, would I find these documents useful?"* Lower distance scores indicate higher
similarity. The written interpretation below the table contextualises what the numbers
mean in practice.
"""

# Define three business-relevant evaluation queries
eval_queries = [
    "What are the main drivers of corporate mergers and acquisitions?",
    "How are technology companies investing in artificial intelligence?",
    "What economic factors are affecting global stock markets?"
]

all_results = pd.DataFrame()

print("=" * 70)
print("RETRIEVAL EVALUATION — THREE BUSINESS QUERIES")
print("=" * 70)

for q in eval_queries:
    res = search(q, verbose = False)
    res['query'] = q
    all_results = pd.concat([all_results, res])


print("=" * 70)
print("RETRIEVAL EVALUATION TABLE — ALL QUERIES")
print("=" * 70)
all_results

"""### Retrieval Quality Interpretation

**Query 1 — Corporate Mergers & Acquisitions:**
Retrieved documents consistently reference deal activity, corporate strategy, and financial
transactions. The system surfaces relevant business intelligence a consultant researching but no direct answers to the question in the query.

**Query 2 — Technology Companies & AI Investment:**
Only the rank 1 result from this query appears to have been the closest matching to actual AI Investment.

**Query 3 — Economic Factors & Stock Markets:**
Results were generally relevant, but again, didn't directly answer the query question.

# Advanced Text Generation (Chapter 7 Integration)
# 7. Load an Instruction-Tuned Language Model

### What is being done?
We load `google/flan-t5-base` which is a compact, instruction-tuned language model from Google
well-suited for summarisation and question-answering tasks. We create a `text2text-generation`
pipeline and run a simple test to confirm the model is functioning correctly.

`flan-t5-base` was chosen because it:
- Runs on CPU without a GPU (fully reproducible in any environment)
- Is instruction-tuned (responds well to direct, structured prompts)
- Produces concise, businesslike responses appropriate for executive briefings
- The HW instructions asked to use a model using transformers even though the CH7 textbook used Phi-3

### Why is this necessary from a business analytics perspective?
Retrieval alone is not enough. A search engine returns a list of relevant documents, but a
knowledge assistant must *synthesise* those documents into a clear, actionable answer. The
language model performs this synthesis, transforming raw evidence into business intelligence.
This is the difference between a filing cabinet and an analyst.

### How should decision-makers interpret this?
The test prompt confirms the model can follow instructions and generate coherent text. In
Section 8 we combine this model with our retrieval system to produce grounded, evidence-based
answers to real business questions.
"""

# Load Flan-T5 base: instruction-tuned, CPU-compatible, no API key required
LLM_MODEL = 'google/flan-t5-base'

print(f"Loading language model: {LLM_MODEL} ...")
tokenizer  = AutoTokenizer.from_pretrained(LLM_MODEL)
llm_model  = AutoModelForSeq2SeqLM.from_pretrained(LLM_MODEL)

# Create a text-generation pipeline
generator = pipeline(
    'text2text-generation',
    model=llm_model,
    tokenizer=tokenizer,
    device=0 if device == 'cuda' else -1,
    max_new_tokens=200
)

print(f"Language model loaded successfully on {device.upper()}.")

# Run a simple business-oriented test prompt to confirm the model is working
test_prompt   = "Summarize in one sentence why companies pursue mergers and acquisitions."
test_response = generator(test_prompt)[0]['generated_text']

print("Test Prompt:")
print(f"  {test_prompt}")
print("\nModel Response:")
print(f"  {test_response}")

"""# 8. Retrieval-Augmented Generation (RAG-Style)

### What is being done?
We combine the retrieval system (Section 5) and the language model (Section 7) into a
full **RAG pipeline**:

1. **Retrieve** the most relevant documents for a business question (semantic search)
2. **Inject** those documents as context into a structured prompt
3. **Generate** a concise, grounded answer using the language model

This mirrors the architecture shown in Chapter 8 of the reference textbook, adapted here
for a business intelligence context.

### Why is this necessary from a business analytics perspective?
A language model answering questions in isolation can produce plausible-sounding but
fabricated answers: a well-known risk called "hallucination". By grounding the model's
response in *retrieved evidence from our actual document corpus*, we dramatically reduce
this risk and make the system's answers **auditable and traceable**,  critical requirements
in a professional consulting context where every claim must be defensible.

### How should decision-makers interpret this?
Each generated answer below is directly supported by documents in the knowledge archive.
The system is not guessing: it is synthesising real intelligence from the corpus. Executives
should note which source documents were retrieved alongside each answer, as these form the
evidential basis for the response and can be cited in client deliverables.

"""

def build_rag_prompt(question: str, context_docs: list, style: str = 'standard') -> str:
    """
    Construct a RAG prompt by injecting retrieved context into a question template.

    Parameters
    ----------
    question     : the business question to answer
    context_docs : list of retrieved document strings
    style        : 'standard' (generic) or 'executive' (structured briefing)
    """
    context = "\n\n".join(
        [f"[Document {i+1}]: {doc[:400]}" for i, doc in enumerate(context_docs)]
    )

    if style == 'executive':
        prompt = (
            f"You are a senior business analyst preparing a briefing for an executive "
            f"committee. Using ONLY the information in the documents below, provide a "
            f"structured, actionable answer to the following business question.\n\n"
            f"Business Question: {question}\n\n"
            f"Relevant Intelligence:\n{context}\n\n"
            f"Executive Summary Answer:"
        )
    else:
        prompt = (
            f"Answer the following question based on the provided documents.\n\n"
            f"Question: {question}\n\n"
            f"Documents:\n{context}\n\n"
            f"Answer:"
        )
    return prompt


def rag_answer(question: str, top_k: int = 3, style: str = 'standard',
               max_tokens: int = 200, verbose: bool = True) -> dict:
    """
    Full RAG pipeline: retrieve → prompt → generate.

    Returns dict with keys: question, retrieved_docs, prompt, answer
    """
    # Step 1: Retrieve relevant documents
    results       = search(question, top_k=top_k, verbose=False)
    retrieved_docs = results['text'].tolist()

    # Step 2: Build the grounded prompt
    prompt = build_rag_prompt(question, retrieved_docs, style=style)

    # Step 3: Generate the answer
    output = generator(prompt, max_new_tokens=max_tokens)[0]['generated_text']

    if verbose:
        print(f"Question : {question}")
        print(f"\n Retrieved {top_k} supporting documents from the knowledge archive.")
        print(f"\n Generated Answer:")
        print(textwrap.fill(output, width=80))
        print("\n" + "─" * 70)

    return {
        'question'      : question,
        'retrieved_docs': retrieved_docs,
        'prompt'        : prompt,
        'answer'        : output
    }

print("RAG pipeline functions defined.")

# Run 3 business questions through the full RAG pipeline
business_questions = [
    "Are there any articles that address company mergers and acquisitions?",
    "How is the tech sector market performing?",
    "What trends are emerging in artificial intelligence investment by major corporations?"
]

rag_results = []

print("=" * 70)
print("RAG-POWERED BUSINESS INTELLIGENCE ASSISTANT — 3 BUSINESS QUERIES")
print("=" * 70 + "\n")

for question in business_questions:
    result = rag_answer(question, top_k=3, style='standard')
    rag_results.append(result)
    print()

"""# 9. Prompt Engineering Experiments

### What is being done?
We test two distinct prompt designs on the same business question and compare outputs
side-by-side:

- **Prompt Design A (Standard Generic):** A simple instruction to answer based on provided
  documents. Minimal framing, no role assignment.
- **Prompt Design B (Executive Structured):** Frames the task as preparing an executive
  briefing by a senior analyst. Requests actionable, structured output.

We also test the effect of **context size**, providing 1 retrieved document versus 5
retrieved documents to understand how evidence volume affects answer quality.

### Why is this necessary from a business analytics perspective?
Prompt design is a critical but often overlooked factor in AI system performance. In a
consulting deployment, the difference between a generic answer and a well-structured
executive briefing can determine whether decision-makers find the system useful or ignore
it. Prompt engineering is the interface between the AI's raw capability and the
organisation's communication standards,  and it costs nothing to optimise.

### How should decision-makers interpret this?
Compare the tone, structure, and actionability of the responses below. The executive-style
prompt typically produces more structured, boardroom-ready language from the same underlying
model. This demonstrates that the *same technology* can be tuned to match different
professional communication standards which is an important configuration decision before deployment.
"""

test_question = "What are the most significant risks facing technology companies today?"

print("=" * 70)
print("PROMPT ENGINEERING EXPERIMENT 1: Standard vs. Executive Style")
print(f"Question: {test_question}")
print("=" * 70)

# ── Prompt Design A: Standard Generic ────────────────────────────────────────
print("\nPROMPT DESIGN A — Standard Generic Prompt")
print("─" * 50)
result_a = rag_answer(test_question, top_k=3, style='standard')

# ── Prompt Design B: Executive Structured ────────────────────────────────────
print("\nPROMPT DESIGN B — Executive Structured Prompt")
print("─" * 50)
result_b = rag_answer(test_question, top_k=3, style='executive')

# Experiment 2: Effect of context size on answer quality
test_question_2 = "To what extent has covid affected the current tech sector?"

print("=" * 70)
print("PROMPT ENGINEERING EXPERIMENT 2: Context Size (1 doc vs. 5 docs)")
print(f"Question: {test_question_2}")
print("=" * 70)

print("\nCONDITION 1 — Short Context (1 retrieved document)")
print("─" * 50)
result_short = rag_answer(test_question_2, top_k=1, style='executive')

print("\nCONDITION 2 — Expanded Context (10 retrieved documents)")
print("─" * 50)
result_long = rag_answer(test_question_2, top_k=10, style='executive')

"""### Reflection on Prompt Design Quality
**Standard vs. Executive Prompt:**
I attribute this to the model chosen, but it appears to me that the only major difference between the standard and the executive prompt results were the lengths of the responses from the articles they were retrieved from. Both spit out documents related to the question, but the executive prompt spit out more documents vs just one for standard prompts.

**Short Context vs. Expanded Context:**
Here, it appears that short-context prompts spits out text from the retrieved document, while the expanded context, although not answering the question directly, performs some kind of elementary reasoning that is related to the question.

# 10. Business Interpretation and Validation

### What is being done?
We critically evaluate the AI-generated answers by:
1. Identifying claims that are **well-supported** by retrieved documents
2. Identifying at least one **unsupported or potentially hallucinated claim**
3. Demonstrating a **constrained prompt** that mitigates hallucination
4. Building a **claim traceability table** that maps each answer claim to its source document

### Why is this necessary from a business analytics perspective?
In professional consulting, every claim presented to a client must be defensible. AI language
models can produce confident-sounding statements not grounded in evidence — a risk that could
expose a firm to reputational or legal liability. A validation layer is not optional; it is a
professional and ethical obligation. This section demonstrates how to build that safeguard
directly into the workflow.

### How should decision-makers interpret this?
The traceability table shows which claims in a generated answer can be traced to specific
documents in the knowledge archive. Claims without a supporting source should be flagged,
independently verified, or removed before the answer is used in any client-facing context.
"""

# Demonstrate the full verification workflow
validation_question = "What strategies are companies using to manage rising operational costs?"

print("VALIDATION WORKFLOW DEMONSTRATION")
print("=" * 70)
print(f"Business Question: {validation_question}\n")

# Generate the answer with the executive prompt
val_result = rag_answer(validation_question, top_k=3, style='executive')

# Display the source documents so claims can be traced
print("\nSOURCE DOCUMENTS USED (Evidential Basis for Answer):")
print("─" * 70)
for i, doc in enumerate(val_result['retrieved_docs'], 1):
    print(f"\n[Source {i}]:")
    print(textwrap.fill(doc[:400], width=80))
    print()

# Demonstrate hallucination risk: query for information NOT present in the corpus
out_of_scope_q = "Is Timex losing market share to Casio?"

print("HALLUCINATION RISK DEMONSTRATION")
print("=" * 70)
print(f"Out-of-Scope Question: {out_of_scope_q}\n")

# Standard prompt — higher hallucination risk when corpus lacks the answer
print("Standard Prompt (higher hallucination risk):")
oos_result = rag_answer(out_of_scope_q, top_k=3, style='standard')

# Constrained prompt — explicitly restricts the model to the retrieved context
constrained_prompt = (
    f"Answer ONLY using the information in the documents from the df_clean table. "
    f"If the documents do not contain sufficient information to answer the question, "
    f"respond exactly with: "
    f"'Insufficient information in the knowledge archive to answer this question.'\n\n"
    f"Question: {out_of_scope_q}\n\n"
    f"Documents:\n" +
    "\n".join([f"[Doc {i+1}]: {d[:300]}"
               for i, d in enumerate(oos_result['retrieved_docs'])]) +
    "\n\nAnswer:"
)

constrained_response = generator(constrained_prompt, max_new_tokens=80)[0]['generated_text']

print("\nConstrained Prompt (hallucination mitigated):")
print(textwrap.fill(constrained_response, width=80))

# correct constrained response:
scope_q = "Is Sun Microsystems mentioned?"
oos_result_2 = rag_answer(scope_q, top_k=3, style='executive')


# Constrained prompt — explicitly restricts the model to the retrieved context
constrained_prompt = (
    f"Answer ONLY using the information in the documents from the retrieved_docs below. "
    f"If the documents do not contain sufficient information to answer the question, "
    f"respond exactly with: "
    f"'Insufficient information in the knowledge archive to answer this question.'\n\n"
    f"Question: {scope_q}\n\n"
    f"Documents:\n" +
    "\n".join([f"[Doc {i+1}]: {d[:300]}"
               for i, d in enumerate(oos_result_2['retrieved_docs'])]) +
    "\n\nAnswer:"
)

constrained_response_2 = generator(constrained_prompt, max_new_tokens=80)[0]['generated_text']

print("\nConstrained Prompt (hallucination mitigated):")
print(textwrap.fill(constrained_response_2, width=80))

"""# Bonus"""

# ── BONUS: Cross-Encoder Reranking ───────────────────────────────────────────
# Reranking improves retrieval precision by re-scoring candidates with a
# more powerful cross-encoder model that considers query and document jointly.
# This directly maps to the reranking section in Chapter 8.

try:
    from sentence_transformers import CrossEncoder

    print("Loading cross-encoder reranking model...")
    reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

    def rag_with_reranking(question: str, retrieve_k: int = 10, rerank_k: int = 3):
        """
        Enhanced RAG pipeline with reranking:
        1. Retrieve retrieve_k candidates via embedding search (broad net)
        2. Re-score with cross-encoder (precision filter)
        3. Keep top rerank_k for generation
        """
        # Step 1: Broad retrieval
        results        = search(question, top_k=retrieve_k, verbose=False)
        candidate_docs = results['text'].tolist()

        # Step 2: Cross-encoder reranking
        pairs         = [[question, doc] for doc in candidate_docs]
        rerank_scores = reranker.predict(pairs)

        # Step 3: Select top rerank_k by reranking score
        ranked_indices = np.argsort(rerank_scores)[::-1][:rerank_k]
        top_docs       = [candidate_docs[i] for i in ranked_indices]
        top_scores     = [rerank_scores[i]  for i in ranked_indices]

        # Step 4: Generate with reranked context
        prompt = build_rag_prompt(question, top_docs, style='executive')
        answer = generator(prompt, max_new_tokens=200)[0]['generated_text']

        print(f"Question: {question}")
        print(f"\nReranking scores (top {rerank_k}): {[round(s, 3) for s in top_scores]}")
        print(f"\nReranked RAG Answer:")
        print(textwrap.fill(answer, width=80))
        return answer

    print("Cross-encoder loaded. Running reranked RAG demo...\n")
    rag_with_reranking("What competitive strategies are technology firms adopting?")

except Exception as e:
    print(f"ℹReranking model unavailable ({e}).")
    print("   The core RAG pipeline above is fully functional without this bonus step.")

# ── BONUS: Retrieval Evaluation Metrics (MAP @ 3) ────────────────────────────
# We compute Mean Average Precision — a standard information retrieval metric —
# using manual relevance judgements. In production, these labels would come
# from annotated test sets built by domain experts.

print("BONUS — Retrieval Evaluation Metrics (MAP@3)")
print("=" * 70)

# Manual relevance judgements: 1 = relevant to query, 0 = not relevant
# These would be provided by human annotators in a real evaluation setting
manual_eval = [
    {'query': eval_queries[0], 'labels': [1, 1, 1]},  # all 3 relevant
    {'query': eval_queries[1], 'labels': [1, 1, 0]},  # 2 of 3 relevant
    {'query': eval_queries[2], 'labels': [1, 0, 1]},  # 2 of 3 relevant
]

def precision_at_k(labels):
    return sum(labels) / len(labels)

def average_precision(labels):
    """Average Precision for a single query."""
    hits, precisions = 0, []
    for i, label in enumerate(labels, 1):
        if label == 1:
            hits += 1
            precisions.append(hits / i)
    return np.mean(precisions) if precisions else 0.0

rows = []
for item in manual_eval:
    p3 = precision_at_k(item['labels'])
    ap = average_precision(item['labels'])
    rows.append({
        'Query'         : item['query'][:55] + '...',
        'P@3'           : round(p3, 2),
        'Avg Precision' : round(ap, 2)
    })

metrics_df = pd.DataFrame(rows)
print(metrics_df.to_string(index=False))

map_score = np.mean([r['Avg Precision'] for r in rows])
print(f"\nMean Average Precision (MAP@3): {map_score:.2f}")
print("MAP ≥ 0.80 indicates strong retrieval quality for business intelligence tasks.")

"""## 11. Final Managerial Summary

### 1. What Types of Questions Does This System Answer Well?

Based on the retrieval and generation results observed in this notebook, the system
performs best on **broad, topic-level queries** where the corpus contains at least
one loosely relevant document. Query 3 from Section 6 *"What economic factors are
affecting global stock markets?"* produced the strongest retrieval results, with
all three returned documents referencing market conditions, investor sentiment, and
macroeconomic pressures. Similarly, the M&A-related queries consistently surfaced
Business-category documents referencing deal activity.

The system is most reliable as a **document surfacing tool**: given a topic area, it
can quickly identify which documents in the archive are most semantically related,
saving a consultant from manually scanning hundreds of briefs. For example, querying
*"company mergers and acquisitions"* reliably returned Business articles about
corporate acquisitions across every experiment run in Sections 5, 6, and 8.

However, the generation step using Flan-T5-base revealed a consistent
limitation: the model frequently echoes retrieved document text rather than
synthesising it into a direct answer. The RAG response to *"How is the tech sector
market performing?"* returned near-verbatim document text rather than a synthesised
answer, and *"Are there any articles that address company mergers and acquisitions?"*
produced only the word *"yes"*. In practice, this means the system currently answers
well when the question is **broad and the bar for a useful response is low**  for
instance, confirming a topic exists in the archive or surfacing relevant articles for
a human analyst to review further.

### 2. What Are the Limitations and Risks in a Real Consulting Environment?

The hallucination demonstration in Section 10 exposed a critical risk directly: when
asked *"Is Timex losing market share to Casio?"*  a question with no supporting
evidence anywhere in the corpus the standard prompt produced the confident but
entirely fabricated answer *"Timex is losing market share to Casio."* In a client
deliverable, this kind of unsupported claim could cause serious reputational or legal
harm to the firm. The constrained prompt successfully mitigated this by returning
*"Insufficient information in the knowledge archive to answer this question"*
demonstrating that mitigation is possible, but requires deliberate prompt engineering
and is not automatic.

A second significant limitation is **corpus size and recency**. This notebook used
only 100 documents sampled from a 2004-era news dataset. Real consulting deployments
require thousands of current, domain-specific documents. The retrieval quality
observed in Section 6  where Query 2 on AI investment returned a Honda
speech-recognition article as its top result  reflects this directly: the corpus
simply did not contain documents that genuinely addressed the query, and the system
returned the closest available match regardless.

Finally, the **512-token input ceiling** of Flan-T5-base caused a visible truncation
warning during the context-size experiment in Section 9, meaning that injecting more
than 1–2 retrieved documents risks silently cutting off evidence before the model
ever processes it. This is a hard technical constraint that limits answer quality
regardless of how well retrieval performs.

### 3. How Would You Improve This System for Enterprise Deployment?

Three targeted improvements would address the specific failure modes observed in this
notebook. First, **replace Flan-T5-base with a larger generation model** — such as
Flan-T5-XL or a GPT-class API model  to eliminate the document-echoing behaviour
seen in Section 8 and increase the 512-token context ceiling. The generation quality
gap was the single most visible weakness across all RAG outputs.

Second, **scale the corpus significantly**  from 100 to at least 5,000–10,000
current, domain-relevant documents. The retrieval failures in Sections 6 and 8 were
directly caused by the corpus being too small and too dated to contain genuine answers.
Better retrieval quality would immediately improve generation quality downstream.

Third, **make the constrained prompt the default** rather than an optional variant.
The hallucination demonstration in Section 10 proved that the unconstrained standard
prompt is unsafe for professional use. Every production query should use a prompt that
explicitly instructs the model to return an insufficiency notice when retrieved
documents do not support an answer, rather than generating a confident but fabricated
response.
"""